azure:
  api_key: "your_azure_api_key"
  api_version: "2023-05-15"
  azure_endpoint: "https://your-resource.openai.azure.com/"

deepseek:
  api_key: "sk-ef6c8699ba4340a0b9dc0e4bf5e58134"
  base_url: "https://api.deepseek.com/v1"